---
title: "01 - Chapter One - Student Performance, Secondary Schools"
author: "Nima Niarad"
date: "7/23/2021"
output:
  rmarkdown::github_document: default
  rmarkdowngithub_document: default
---

<style> body {text-align: justify} </style> <!-- Justify text. -->

## Introduction

Students are one of the biggest assets of a country. Those who will play a key role in the near future and will be in charge of the most important parts of a country. The economic and social development of any country is directly related to students' educational performances. 

Several studies have been done in this area like working on sex and regions of weak schools and students, studying distance learning and its effects on students’ grades. 

The student's academic performance can be measured in several ways. Most of the data analysts around the world have used grades to measure the student performance or the result of a particular subject. Here, I used first, second and final grades as the main dependent variables. 

On the other hand, many factors affect students' grades. For example, gender, students 'age, families and their education, student study hours, extracurricular activities, the quality of children relationship with parents, students' mental and physical health, all greatly influence their academic performance. There are many other important factors, such as the size of classes, the number of students in a class, etc., that are assumed to be in line with international standards.

This project is conducted to investigate these factors that can affect the academic achievement of secondary school students which is mostly about their grades.  

It is based on student profiles on the basis of data collected through assessment from students of two secondary schools in Portugal. The core class is mathematic as it is an important subject to have more successful individuals in the communities. 
I intend using the available data to analyze and provide suggestions for improving the quality of education and students’ performances.


## Main Questions

What are the most important factors influencing student performance?

Which group of students performed better than the others?  Is Gender a Role?

To what extent are parents' education effective in their children's success?

What group and number of students want to continue their education?

How can students' performance be improved?

The results can be useful for students, parents and educators to make some important decision to improve academic achievements and introduce individuals with high knowledge and ability to the community.


