---
title: "02 - Chapter Two - Data"
author: "Nima Niarad"
date: "7/23/2021"
output:
  rmarkdown::github_document: default
  rmarkdowngithub_document: default
---

<style> body {text-align: justify} </style> <!-- Justify text. -->

## Data

The data contains both numerical and categorical variables. It gives me the opportunity to analyze them in a wider range with a variety of methods.

A 20-point grading scale is used, where 0 is the lowest grade and 20 is the perfect score. Students are evaluated three times and the last evaluation, G3, corresponds to the final grade.

**Discrete Variables**

-	sex: student’s sex (binary: female or male)

-	age: student’s age (numeric: from 15 to 22)

-	school: student’s school (binary: Gabriel Pereira or Mousinho da Silveira)

-	address: student’s home address type (binary: urban or rural)

-	Pstatus: parent’s cohabitation status (binary: living together or apart)

-	Medu: mother’s education (numeric: from 0 to 4a)

-	Mjob: mother’s job (nominalb)

-	Fedu: father’s education (numeric: from 0 to 4a)

-	Fjob: father’s job (nominalb)

-	guardian: student’s guardian (nominal: mother, father or other)

-	famsize: family size (binary: ≤ 3 or > 3)

-	famrel: quality of family relationships (numeric: from 1 – very bad to 5 – excellent)

-	reason: reason to choose this school (nominal: close to home, school reputation, course preference or other)

-	traveltime home to school travel time (numeric: 1 – < 15 min., 2 – 15 to 30 min., 3 – 30 min. to 1 hour or 4 – > 1 hour).

-	studytime: weekly study time (numeric: 1 – < 2 hours, 2 – 2 to 5 hours, 3 – 5 to 10 hours or 4 – > 10 hours)

-	failures: number of past class failures (numeric: n if 1 ≤ n < 3, else 4)

-	schoolsup: extra educational school support (binary: yes or no)

-	famsup: family educational support (binary: yes or no)

-	activities: extra-curricular activities (binary: yes or no)

-	paidclass: extra paid classes (binary: yes or no)

-	internet: Internet access at home (binary: yes or no)

-	nursery: attended nursery school (binary: yes or no)

-	higher: wants to take higher education (binary: yes or no)

-	romantic: with a romantic relationship (binary: yes or no)

-	freetime: free time after school (numeric: from 1 – very low to 5 – very high)

-	goout: going out with friends (numeric: from 1 – very low to 5 – very high)

-	Walc: weekend alcohol consumption (numeric: from 1 – very low to 5 – very high)

-	Dalc: workday alcohol consumption (numeric: from 1 – very low to 5 – very high)

-	health: current health status (numeric: from 1 – very bad to 5 – very good)

**Continuous Variables**

-	absences: number of school absences (numeric: from 0 to 93)

-	G1: first period grade (numeric: from 0 to 20)

-	G2: second period grade (numeric: from 0 to 20)

-	G3: final grade (numeric: from 0 to 20)








